name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Target
      id: cache-target
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-target
    - name: Cache Cargo
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: /home/runner/.cargo
        key: ${{ runner.os }}-cargo
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
        target: wasm32-unknown-unknown
    - name: Install WASM32 Runner
      run: cargo install wasm-server-runner
    - name: Bench
      run: cargo bench --verbose
    - name: Bench (wasm32)
      run: RUSTFLAGS="--cfg=web_sys_unstable_apis" CARGO_TARGET_WASM32_UNKNOWN_UNKNOWN_RUNNER=wasm-bindgen-test-runner cargo bench --target wasm32-unknown-unknown --verbose
